apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: macula-arcade
  namespace: macula
  annotations:
    external-dns.alpha.kubernetes.io/hostname: arcade2.macula.local
spec:
  ingressClassName: nginx
  rules:
  - host: arcade2.macula.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: macula-arcade
            port:
              number: 80
