apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  # MetalLB native manifests (includes namespace)
  - https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
  - ipaddresspool.yaml
  - l2advertisement.yaml
